### PR TITLE
JENKINS-71587: Add option to prevent fast failing of backup process

### PR DESCRIPTION
**Pull request by krulls**
Description see https://issues.jenkins.io/browse/JENKINS-71587
The changes add a new configuration option which is set to true by default: The option allows to configure if the plugin fails fast when running into an exception in the process of backing up files from the Jenkins data.

### Testing done

Build locally with "mvn clean package". Was not capable to write a fitting unit test as the implementation is quite complex.
Tested the logic with a local Jenkins instance:
- left ThinBackup settings with default (thus it fails fast when it runs into an exception in the backup process)
- then ran a backup while having a file within the data which is not accessible to the jenkins user
- the plugin stops with an IOException (as expected)
- changed the setting to use the new option and prevent fast failing
- ran a backup again
- the plugin just logs the IOException and continues with the process and finishes successfully

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by krulls** [comment]
Please be aware that I am out of office until including Thursday, 27th of July 2023.

**Comment by StefanSpieker** [comment]
@krulls First of all thanks for the error report and the PR addressing this. On a first look it seems a quite good change. I will test it during the week and provide you some feedback next weekend.

**Comment by StefanSpieker** [comment]
I tested it so far. On Windows everything looks fine. I will give it another try on Linux before I merge it and cut a release.

**Review by StefanSpieker — APPROVED** [review]
Sorry, it took me a little lionger, but all tests were fine. Thanks again!

**Comment by krulls** [comment]
Great, thank you for the timely release!

**Pull request merged**
