### PR TITLE
JcasC Compatibility

### PR DESCRIPTION
**Pull request by sladyn98**
This PR aims to add JCasC Compatibility. I have tried adding the descriptor classes, it seems that the main class might need to implement  simple build step, though I am not too sure.

### CODE REVIEW

**Comment by sladyn98** [comment]
CC: @tofuatjava

**Comment by sladyn98** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/issues/809

**Comment by alecharp** [comment]
@sladyn98 it would be great to have a test to validate the behaviour. Please, have a look at https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md#how-to-test. Adding a YAML file would also show a valid example of how to configure the plugin with JCasC.

**Comment by sladyn98** [comment]
@alecharp Yeah the plugin does not extend the build step behaviour and I hence the descriptor is unable to find the superclass. I am working on a workaround for it .

**Pull request closed without merging**
