### PR TITLE
Included support for the promoted builds plugin and job promotions, addr...

### PR DESCRIPTION
**Pull request by stephenkerrmurphy**
...essing the open issue JENKINS-21472

### CODE REVIEW

**Comment by devshorts** [comment]
I know this issue is old, but can we get some traction here? I'd love to get promotions backed up

**Comment by stephenkerrmurphy** [comment]
Morning Anton, i’m afraid i don't maintain the project — just had the same requirement as you. I’ve an outstanding pull request that addresses promotions if you want to use it, we’ve been using it for the last 12months successfully.

https://github.com/stephenkerrmurphy/thin-backup-plugin

Regards, Stephen.

**Comment by devshorts** [comment]
@stephenkerrmurphy, @tofuatjava now that this is merged is there going to be a new release of the plugin? I would love to upgrade asap

**Comment by stephenkerrmurphy** [comment]
I don’t maintain the plugin unfortunately, that’d be Thomas Fuerer's help you’d need? alternatively of course you could download/build and upload the hpi manually yourself, jenkins does support manual plugin installation.

Stephen.

**Comment by devshorts** [comment]
Cool thanks for the info! I built and updated that way, works like a charm :)

Appreciate it!

**Pull request merged**
